apiVersion: v1
kind: Service
metadata:
  name: {{ include "hospital-app.fullname" . }}-mongodb-service
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: {{ .Values.mongodb.service.port }}
      targetPort: {{ .Values.mongodb.service.port }}
      name: mongodb
  selector:
    app: {{ include "hospital-app.fullname" . }}-mongodb
  type: ClusterIP
