apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hospital-app.fullname" . }}-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  SESSION_SECRET: {{ .Values.app.secrets.sessionSecret | b64enc | quote }}
  JWT_SECRET: {{ .Values.app.secrets.jwtSecret | b64enc | quote }}
  ADMIN_USERNAME: {{ .Values.app.secrets.adminUsername | b64enc | quote }}
  ADMIN_PASSWORD: {{ .Values.app.secrets.adminPassword | b64enc | quote }}
