apiVersion: v1
kind: Service
metadata:
  name: {{ include "hospital-app.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.app.service.type }}
  ports:
    - port: {{ .Values.app.service.port }}
      targetPort: {{ .Values.app.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "hospital-app.fullname" . }}-app
